Presentation:
  path:     /
  defaults: { _controller: AppBundle:Presentation:index }

Experience:
  path:   /experience 
  defaults: { _controller: AppBundle:Presentation:experience}

Formation:
  path:   /formation
  defaults: { _controller: AppBundle:Presentation:formation}

Recherche:
  path:   /recherche
  defaults: { _controller: AppBundle:Presentation:recherche}

Contact:
  path:    /contact
  defaults: { _controller: AppBundle:Contact:index}

Evaluation:
  path:   /evaluation
  defaults: { _controller: AppBundle:Evaluation:evaluation}

Ajouter:
  path:   /ajouter
  defaults: { _controller: AppBundle:Evaluation:ajouter}

