# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  AppBundle\Services\CvAntispam:
    autowire: true
    autoconfigure: true
    arguments:
      - %locale%
      - 10

  AppBundle\Services\EvaluationService:
    autowire: true
    autoconfigure: true

      

